### ISSUE TITLE
ACR fails to show album art while browsing artist albums.

### ISSUE THREAD

**Issue by ianmacd** [henkelis/sonospy#1]
Using the latest version of the ACR on my Nexus One phone, album art thumbnails fail to appear when browsing an artist's albums.

Issue present in SHA fbb37c6d33c04b35d4d1d59bcaa5efad34a6c8c7

**Comment by ianmacd** [comment]
The same issue is present on all Android-based devices.

If I were going to have a go at fixing this, where should I look first?

**Comment by henkelis** [comment]
If you turn debug on and run with -mproxy -mwebserver, you'll see the 
calls that are made for the albumart. That said, it's probably more 
likely that the proxy needs to return the art converted in some way. If 
you run wireshark while browsing the Sonos library from an Android 
controller, you'll see what Sonos returns where albumart is requested 
and can compare that to the proxy.

**Comment by henkelis** [comment]
It appears that this is a bug in the Sonos Android controller - art also doesn't show up for WMP native.

**Comment by henkelis** [comment]
No longer an issue.
