### ISSUE TITLE
scan can't handle path with unicode character

### ISSUE THREAD

**Issue by Barry4679** [henkelis/sonospy#27]
The exception handler doesn't seem to handle the characters, so it is hard to see what is going on. 

The scan failed. 
path:
music_folder=\NAS-PRIMOS01\flac\Amon Düül II

cmd window:
D:\Documents and Settings\BMOSS\My Documents\Sonos Project\henkelis-sonospy-f1dc
 a6c\sonospy>python scan -d Testxxx.db \\NAS-PRIMOS01\flac\Amon\ D  l\ II > t
 estxxx.log
 F:\Do Not backup\Python\lib\cgitb.py:245: DeprecationWarning: BaseException.mess
 age has been deprecated as of Python 2.6
   value = pydoc.text.repr(getattr(evalue, name))

the utility that I used to capture the above image from the cmd window can't handle the characters either too well either, but the name was entered correctly.

log file:
atabase:  D:\Documents and Settings\BMOSS\My Documents\Sonos Project\henkelis-sonospy-f1dca6c\sonospy\Testxxx.db
*\* EXITING on unhandled exception - See errors/ErrorDump-20110608-133927.txt
python ./gettags -d Testxxx.db \\NAS-PRIMOS01\flac\Amon\ Düül\ II

**Comment by henkelis** [comment]
Can you provide:

```
errors/ErrorDump-20110608-133927.txt
```

please.
