### ISSUE TITLE
multi-artist mouseover setting ignored

### ISSUE THREAD

**Issue by Barry4679** [henkelis/sonospy#28]
In pycpoint.ini I have the following:
now_playing_artist=last
now_playing_artist_combiner=' / '
mouseover_artist=all
mouseover_artist_combiner=' / '

When I hover over a track tagged with multiple artists, in the Music Library half of the screen, I see just the last artist (ie. the Now Playing behaviour).

**Comment by henkelis** [comment]
Closed - mouseover removed.
