### ISSUE TITLE
albums with multiple artist tags ignore pycpoint.ini when added to queue

### ISSUE THREAD

**Issue by Barry4679** [henkelis/sonospy#3]
The now_playing_artist property in pycpoint controls how the artist field is set when a track, which has multiple artist tags, is added to the sonos queue.

If I queue a single track with a setting of "now_playing_artist=last" Sonospy correctly causes the track to be queued with the artist set to just the last named artist from the track's artist tag. (ie. the track is queued just the same as Sonos-native would have queued it).

However if I queue a whole album the "now_playing_artist=last" property is ignored. The track is queued with the artist field containing a concatenation of all artists contained in the track's artist tag.

The impact is that the user cannot control how a multi-artist track is scrobbled to Last.fm. ie. Sonospy cannot scrobble the play to match the user's scrobble history which was built while using Sonos-native.

**Comment by ianmacd** [comment]
This may be related to the quoted section of [this message](https://groups.google.com/forum/#!searchin/sonospy-devel/pcdcr$20zp120$20header/sonospy-devel/xhBTSCQK_uY/TGvqhr8cWIEJ).

Specifically, the explanation that whole albums are queued by a ZP, whereas single tracks are queued by the controller.

**Comment by Barry4679** [comment]
If a fix to this issues falls into the too hard basket, due to the issue which Ian has pointed too, my preference would that I was able to configure Sonospy to ignore all but the last artist tag for a track during its scan. This behaviour would emulate Sonos-native's index build.

In this way I could retain the multiple artist tags in my tracks for use outside Sonos & Sonospy, while also maintaining a connection with my sonos-native generated scrobble history at LFM..

**Comment by henkelis** [comment]
You can already instruct sonospy to ignore all but the last artist tag during movetags (that way the data is in the tags table so you only need to change the flag and regen tracks) - use include_artist=last and run a regen (-r).
