### ISSUE TITLE
Scan progress meter only appears in verbose mode.

### ISSUE THREAD

**Issue by Barry4679** [henkelis/sonospy#31]
Scan can be a long running job. Too long without a life sign.

The only way to get a life sign is to set on verbose mode. (You see a "processing file" nnnn" counter ticking over for each track.

A verbose log for a large scan run is humongous. Too large to be of any use.

Can we get a life sign to appear in the other scan modes please. It doesn't need to tick over for every track, each 100 tracks would be ok.

Also the life sign only occurs during the track reading phase. There is no life sign during the db updating phase.

What would ideal would be:
- a count up of track read
- then a new line showing how many tracks to update
- then a count down during the update phase.

**Comment by ianmacd** [comment]
Being able to run a silent scan is a feature. Think of scheduled scan jobs: if all goes well, there's no need for output.

Perhaps different levels of verbosity are needed: --verbose 1, --verbose 2, etc.

Alternatively, there could be just one level of --verbose, but one or more --debug levels. That would enable a distinction between verbose reporting that is still of interest to the end-user, vs, verbose reporting that is only of interest to the developer.

**Comment by Barry4679** [comment]
> Perhaps different levels of verbosity are needed: --verbose 1, --verbose
> 2, etc.

Maybe, but a silent scan probably wouldn't be running in a cmd window. 

> if all goes well, there's no need for output.

It can be a very long running job. The danger is that somebody assumes that it has died or is looping.

**Comment by ianmacd** [comment]
I wouldn't advocate different behaviour when the scan is running in a window than when it's running without a controlling terminal. That would be unusual and confusing, I think.

I recognise the danger you mention, though. Perhaps it will be a non-issue when the scan is performing at expected speed.
