### ISSUE TITLE
Scan got locked in syndrome

### ISSUE THREAD

**Issue by Barry4679** [henkelis/sonospy#34]
Issue #32 (case sensitive scan path) managed to put my db into a locked in state.

The issue wasn't cleared by a -r run.

It showed next to no outward sign other than a a longer than expected update scan run time. The only other error was some messages buried in a huge log file.

It had approx 70 albums that it decided that it wanted to delete. It tried, and failed, to delete them every run. ending with a verbose log file entry of :
Existing file not found: billcallahan_20110515_t13.flac, \NAS-PRIMOS01\flac\Bill Callahan\Berlin, May 2011
DELETE: (u'8392ce8addf8f88fec6a4e012127a7c3', u'236e11b064a3a6c38f0ac94084b265d1', u'The Well (live)', u'Bill Callahan', u'Berlin, May 15th 2011', u'Rocked\nTaped', u'13', u'2011', u'Bill Callahan', u'', u'FLAC', u'501', u'34843692', u'1305958669.0', u'\\NAS-PRIMOS01\flac\Bill Callahan\Berlin, May 2011', u'billcallahan_20110515_t13.flac', u'', u'', u'\\NAS-PRIMOS01\flac\Bill Callahan\Berlin, May 2011\folder.jpg', u'EMBEDDED_1325,36839_\\NAS-PRIMOS01\flac\Bill Callahan\Berlin, May 2011\billcallahan_20110515_t13.flac', u'', u'44100', u'16', u'2', u'audio/x-flac', u'1305958531.0', u'object.item.audioItem.musicTrack', 10, u'876', u'889', u'1307593243.593', u'1307613293.39')
Error processing deletions: disk I/O error

The same thing every update scan run, even after a -r scan.

In the end I had to make another database from scratch.

I still have the db, and have emailed the update scan log to mark

**Comment by henkelis** [comment]
The disk I/O error suggests that there wasn't enough disk space to store 
SQLite's temporary files - given the number of deletes it's possible 
that the journal file was quite large. Before I investigate further can 
you confirm that the area that temp files were stored in was not full 
please.
