### ISSUE TITLE
Specifying a path to the database causes files not to play.

### ISSUE THREAD

**Issue by ianmacd** [henkelis/sonospy#36]
When starting the proxy like this:

```
./sonospy_proxy -wSonospy=`git branch | sed -rne 's/^\* (.+)$/\1/p'`,/usr/local/src/sonospy/sonospy/sonos.sqlite
```

the database is found and used for browsing. Queueing files also works, but they will not play. Sonos says **the file cannot be found**.

Something isn't quite right in the path handling when a path to the DB is given.

This, on the other hand, works:

```
./sonospy_proxy -wSonospy=`git branch | sed -rne 's/^\* (.+)$/\1/p'`,sonos.sqlite
```

**Comment by ianmacd** [comment]
When this problem occurs, _get_Track_ is being invoked with an _objectname_ whose value is **opt**, rather than something like sonos.sqlite.7a603ac1d143d2ac61b84145962e1ad7.flac.

**Comment by henkelis** [comment]
Thanks. When specifying a path, the path gets included in the resource name. When the webserver tries to serve the resource it wrongly assumes there won't be a path and takes the first part of the path as the resource name. I'm coding a fix that correctly removes the path from the resource name.
