### ISSUE TITLE
Empty dates show as underscore when sort is applied.

### ISSUE THREAD

**Issue by ianmacd** [henkelis/sonospy#38]
Empty date tags display as _ in the Artist Album index when this sort is applied:

```
ALL|ALL|ARTIST_ALBUM|2|year||year||ordered by year released|Y
```

**Comment by henkelis** [comment]
They do indeed, by design. Empty tags that you output as prefixes and suffixes are replaced with whatever is in:
    chunk_metadata_empty
in pycpoint.ini.
This is so that you know you have missing data. You should be able to set it to nothing instead.

**Comment by ianmacd** [comment]
Don't I know that I have missing data from the presence of one of the <tt>chunk_metadata_delimiter_*</tt> directives? I suppose they could all be blank or unused.

I'm sure you're right, though. I find the <tt>chunk_metadata_*</tt> all a tad tricky to keep straight in my head.

A more logical default for <tt>chunk_metadata_empty</tt> might be **?**.

Close this issue at will.

**Comment by henkelis** [comment]
Default changed to ?.
