### ISSUE TITLE
Playlists do not show up under proxy's entry in Music Services

### ISSUE THREAD

**Issue by ianmacd** [henkelis/sonospy#4]
Playlists are ignored by the proxy and do not show up under their heading in the proxy's entry under Music Services.

This is almost an enhancement request, but I'm filing it as a bug due to the fact that the **Playlists** heading is already present and can't be deactivated, so user expectation is that it also be populated.

**Comment by ianmacd** [comment]
I hate to reopen this, but native Sonos also supports WPL and PLS files.

**Comment by henkelis** [comment]
To save me looking, does Sonos support streams in playlists, and does it honour the title in the playlist or the tags?

Also, what about nesting?

**Comment by ianmacd** [comment]
I'm fairly sure that I've tried streams and found they didn't work.

As for the title, I don't know, but I would guess that it honours the tags.

I don't know about nesting, either, but would be surprised if Sonos honoured that. The implementation seems to be lip service to the feature, as you might expect for something regarded as _legacy_. They want you to use native Sonos playlists, so support for imported ones isn't great.

**Comment by henkelis** [comment]
On 08/24/2011 11:09 AM, ianmacd wrote:

> I'm fairly sure that I've tried streams and found they didn't work.

I could probably fairly easily get streams to work, would be a neat way 
of creating radio presets.
