### ISSUE TITLE
.m4a extension ignored by scan

### ISSUE THREAD

**Issue by ianmacd** [henkelis/sonospy#44]
From <tt>scan.ini</tt>:

```
file_name_exclusions=.ds_store,desktop.ini,thumbs.db
file_extension_exclusions=.txt,.csv,.jpg,.png,.gif,.ffp,.md5
```

but <tt>scan</tt> still ignores .m4a files, which are just AACs:

```
$ file /media/audio/agnes_obel/itunes/riverside_single_remix/01_riverside_lulu_rouge_remix.m4a
/media/audio/agnes_obel/itunes/riverside_single_remix/01_riverside_lulu_rouge_remix.m4a: ISO Media, MPEG v4 system, iTunes AAC-LC
```

From <tt>scanlogverbose.txt</tt>:

```
Filetype not catered for: /media/audio/agnes_obel/itunes/riverside_single_remix/01_riverside_lulu_rouge_remix.m4a
```

I'm not an iTunes user, but this is a shows-topper for those who are.

**Comment by ianmacd** [comment]
gettags.py has code for handling MP4 files, but it's commented out. Why?

If I uncomment it and scan, I can add .m4a files to the DB, queue and play them, so I'm curious why the scanning code for them has been disabled.

**Comment by henkelis** [comment]
If only I could remember. It probably relates to using Easy vs not, 
though it may be that it broke something else. Or maybe I did it and 
forgot to put it back in :o)

I'll have to investigate unless someone wants to do testing of all file 
types concurrently.

**Comment by ianmacd** [comment]
I've just done a full 81000+ file scan and all looks well.

Mind if I commit the change, so that others can see how it fares for them?

**Comment by henkelis** [comment]
That's fine. It may have related to comments, I had to find a way to 
propagate them through, and the Mutagen Easy module didn't allow that. 
We needed them then for virtuals and now we don't, so all may be well.

**Comment by ianmacd** [comment]
Many thanks. Pushing now.

It feels nice to fix an issue, even if I'm using your code to do it. :-)

Fixed in commit 41357b231a5c2fef6216f8a03ac9b18c38fa8c18.

**Comment by henkelis** [comment]
Does album art work for .m4a?

**Comment by ianmacd** [comment]
Yep. You did a fine job. :-)
