### ISSUE TITLE
empty databases are seen as valid by control points

### ISSUE THREAD

**Issue by chowanec** [henkelis/sonospy#49]
Ideally, we'd have an ini file option to hide empty databases.  They can get created pretty easily with the extract subset of commands from the scan command.  I create a database every night of what was inserted <=7d.  On the 8th day, it's possible to have an empty database which will still show up in the controller.

**Comment by chowanec** [comment]
henk, does the fix invole an ini setting, or are we just ignoring empties?

**Comment by henkelis** [comment]
Just ignoring empties. If there are no records in the tracks table, it 
returns an error message.
