### ISSUE TITLE
playlist.sp doc file not updated with new virtual option

### ISSUE THREAD

**Issue by Barry4679** [henkelis/sonospy#51]
The documentation file at \sonospy\virtuals\playlist.sp has not been updated to describe the new folder method of adding tracks to a virtual.

**Comment by henkelis** [comment]
That's why this branch is called unstable. The commit gives details.

The final approach has not been decided, it's out for review via testing before finalising and documenting.

**Comment by Barry4679** [comment]
When you get to my age you will learn that it is best to write something down as soon as you think of it.

.. this ticket I mean ... not your documentation :-)

**Comment by henkelis** [comment]
Fixed
