### ISSUE TITLE
Code that caters for duplicates slow when there are many dups

### ISSUE THREAD

**Issue by henkelis** [henkelis/sonospy#6]
When a user has lots of duplicates of the same track, for instance when they have lots of non-tagged tracks, creating the database slows down massively.

**Comment by henkelis** [comment]
The code that assigns duplicates starts from one each time and works up incrementally trying to insert a record. That code should be changed to query for the next available slot instead.

**Comment by Barry4679** [comment]
Could this be handled by rejecting, with error message to the log, any duplicate beyond n copies ?

**Comment by henkelis** [comment]
Fixed in initial release
