### ISSUE TITLE
Line-In

### ISSUE THREAD

**Issue by nlagaros** [henkelis/sonospy#66]
There does not seem to be a facility to select Line-In as an input.  It is not listed in the rootMenus of the Sonos ZonePlayers as it apparently used to be.

**Comment by ianmacd** [comment]
This has nothing to do with Sonospy. Please post general Sonos issues on the Sonos forums.

**Comment by henkelis** [comment]
I think he was referring to the loss of Line-In as a menu item in the Sonospy GUI. Something else Sonos have changed has resulted in the line-in code not being reached - I've uploaded a patch, please test it out.

**Comment by nlagaros** [comment]
It worked perfectly!  Thanks so much Mark.

**Comment by ianmacd** [comment]
Apologies. I didn't realise anyone was using the GUI and assumed the report was in error, as it was unrelated to the proxy.
