### ISSUE TITLE
not able lo load more than one separate Media-"servers" / DBs

### ISSUE THREAD

**Issue by Viper525** [henkelis/sonospy#73]
I tried to start the proxy as documented for using multiple Media servers for having a better overview with the following command:

./sonospy_proxy -wSonospy=MusicBay-Alben_etc,Alben_etc.db -wSonospy=MusicBay-Interpreten,Interpreten.db -wSonospy=MusicBay-Charts,Charts.db -wSonospy=MusicBay-Medleys,Medleys.db

But I only see the first Media Server "MusicBay-Alben_etc".

What can I do to use more than instances?

**Comment by henkelis** [comment]
With the Windows Media Player interface (using -w) you can only show one 
media server - Sonos only looks for it on ports that WMP uses.

If you use the SMAPI interface (using -s), you can show multiple media 
servers. You can use both -w and -s together, but only one -w with one 
or more -s.

Mark.

**Comment by Viper525** [comment]
Hi, will Sonos be able to "see" the SMAPI servers?
I just tried and don't see any Server within the sonos Software.

Do I have to free special ports in the firewall?

Viper

**Comment by henkelis** [comment]
Yes. You will have to add them under More Music the first time you use 
them though.

**Comment by Viper525** [comment]
Yout mean "add music services"? What do I have to select there? Even at the sonos lab "directory" I don't see anything making sense to me. THere is not one entery that isn't about registration.
I started sonospy with the followong comand:
./sonospy_proxy -sSonospy=MusicBay-Alben_etc,Alben_etc.db -wSonospy=MusicBay-Medleys,Medleys.db
 (just to have one SMAPI server plus one WMP Server for checking if "anything" is running.

**Comment by henkelis** [comment]
Add -r to the command line, that tells Sonospy to inform Sonos of the 
SMAPI server(s). Once you've done that you should see an entry for 
MusicBay-Alben_etc in Add Music  Services.

**Comment by Viper525** [comment]
perhaps I'm a little bit stupid atm for some reason, but I don't see the server.
New command: ./sonospy_proxy -sSonospy=MusicBay-Alben_etc,Alben_etc.db -r -wSonospy=MusicBay-Medleys,Medleys.db
I still see the Medley-Server as usual, but not the "Alben"-Server under add music services.
![01](https://cloud.githubusercontent.com/assets/8208705/3636031/12d1e744-0f9b-11e4-835e-114b9beaf9b2.PNG)
![02](https://cloud.githubusercontent.com/assets/8208705/3636032/17da32aa-0f9b-11e4-888f-62eadbadb08c.PNG)

**Comment by henkelis** [comment]
It sounds like your PC isn't finding your Zones.

Do you have the correct ports open in the firewall on the PC you're 
running Sonospy on (WMP ports must be open for that to work, but what 
about the others)? They're in the readme.

You can run:

```
 python sonospy/showdevices.py
```

to see if it can see your zones.

**Comment by Viper525** [comment]
Yeah! That seems to be the way. But I found out that it's working by stopping the firewall completly, as I opened all the ports given in the readme file:
![01](https://cloud.githubusercontent.com/assets/8208705/3636131/e0f48e36-0fa2-11e4-8470-36330d4c8755.PNG)
In addition I opened 50103+50104 and 10245-10250
Any idea what's going wrong at my configuration (it's a suse 12.2 system with only the console running and I'm using yast in the console to make the configurations.)

And here's the ini:
![02](https://cloud.githubusercontent.com/assets/8208705/3636141/767d0f1e-0fa3-11e4-864f-35e94acb1a36.PNG)

**Comment by Viper525** [comment]
okay, I've done it with "iptraf". I looked what ports are called from the players, etc. and opened them in the firewall. Working great now, but I still have no idea where to find those ports.

So: Thanks a lot! Thas was a great helping! :-)

**Comment by henkelis** [comment]
Which ports you open in the 50100 range depend on what 
controlpoint_port, proxy_port, comms_port and smapi_port are set to in 
the ini. If you run multiple SMAPI servers you need to extend that range 
too.
