### ISSUE TITLE
Searching Within Sonos App

### ISSUE THREAD

**Issue by mosukinu** [henkelis/sonospy#78]
Hi,

Just completed an install running two instances and all working OK.

When I search through music, it only brings up results that start with the search phrase e.g. if I search for 'Big' then an album called 'Big Soup' is returned but if I search for 'Soup' then no results are returned.

Is this expected behaviour?

Thanks

**Comment by henkelis** [comment]
I'll have to check, but IIRC it defaults to searching from the start of the string (with an implied wildcard at the end). You should be able to put '%' at the start to get the behaviour you're after - I'll check whether that's an ini option somewhere. 

Mark. 

----- Original Message -----

**Comment by mosukinu** [comment]
Hi Mark, 

Using % as a wildcard does indeed work as described with the out-of-the-box .ini settings. Many thanks for the quick reply!
