### ISSUE TITLE
Incomplete music files will be processed

### ISSUE THREAD

**Issue by henkelis** [henkelis/sonospy#8]
If a user has partial music files in their folder to be scanned, scan will process them (e.g. music.mp3.part).

**Comment by henkelis** [comment]
Probably need to add an ini entry to allow a list of extensions to be excluded.

**Comment by Barry4679** [comment]
The exclusion list in the ini file is a good idea. Would it mean the messages like this disappear:

"Filetype not catered for: \MyNas\flac\Afrocubism\Afrocubism\Afrocubism - Afrocubism.txt"

**Comment by henkelis** [comment]
Yes.
